version: "3"
services:

  backend:
    container_name: kupipodariday-backend
    build: 
      context: ./backend
      dockerfile: Dockerfile
    env_file: 
      - ./backend/.env
    restart: always
    ports:
      - "4000:3000"
    networks:
      - network
      - database-network
    links:
      - postgres
    depends_on:
      - postgres

  frontend:
    container_name: kupipodariday-frontend
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    networks:
      - network
    restart: always   

  postgres:
    container_name: postgres
    image: "postgres:12"
    networks:
      - database-network
    # ports:
    #   - "5432:5432"
    volumes:
      # - postgres_data:/data/database
      # - volume:/var/lib/postgresql/data
      # - postgres_data:/data/postgres
      - volume:/data/postgres
    env_file: 
      - ./backend/.env
    restart: always  

volumes:
  volume:
    driver: local    

# networks:
#   database-network: {}

networks:
  network:
    driver: bridge
  database-network: 
    driver: bridge
    internal: true
    